/*
 * Copyright (C) 2020 PekinSOFT Systems
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * *****************************************************************************
 * *****************************************************************************
 *  Project    :   Northwind-Basic
 *  Class      :   LoadEntryDialog.java
 *  Author     :   Sean Carrick
 *  Created    :   Mar 16, 2020 @ 10:59:13 AM
 *  Modified   :   Mar 16, 2020
 *  
 *  Purpose:
 *  
 *  Revision History:
 *  
 *  WHEN          BY                  REASON
 *  ------------  ------------------- ------------------------------------------
 *  Mar 16, 2020  Sean Carrick        Initial creation.
 * *****************************************************************************
 */
package com.pekinsoft.northwind.desktop;

import com.pekinsoft.northwind.basic.Application;

/**
 *
 * @author Sean Carrick
 */
public class LoadEntryDialog extends javax.swing.JInternalFrame {

    /**
     * Creates new form LoadEntryDialog
     */
    public LoadEntryDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTrip = new javax.swing.JLabel();
        txtTrip = new javax.swing.JTextField();
        txtOrder = new javax.swing.JTextField();
        lblOrder = new javax.swing.JLabel();
        lblBeginOdo = new javax.swing.JLabel();
        txtBeginOdo = new javax.swing.JFormattedTextField();
        lblEndOdo = new javax.swing.JLabel();
        txtEndOdo = new javax.swing.JFormattedTextField();
        pnlPickup = new javax.swing.JPanel();
        lblEarlyDatePU = new javax.swing.JLabel();
        txtEarlyDatePU = new javax.swing.JFormattedTextField();
        lblEarlyTimePU = new javax.swing.JLabel();
        txtEarlyTimePU = new javax.swing.JFormattedTextField();
        lblLateDatePU = new javax.swing.JLabel();
        txtLateDatePU = new javax.swing.JFormattedTextField();
        lblLateTimePU = new javax.swing.JLabel();
        txtLateTimePU = new javax.swing.JFormattedTextField();
        pnlDelivery = new javax.swing.JPanel();
        lblEarlyDateDel = new javax.swing.JLabel();
        txtEarlyDateDel = new javax.swing.JFormattedTextField();
        txtEarlyTimeDel = new javax.swing.JFormattedTextField();
        lblEarlyTimeDel = new javax.swing.JLabel();
        lblLateDateDel = new javax.swing.JLabel();
        txtLateDateDel = new javax.swing.JFormattedTextField();
        txtLateTimeDel = new javax.swing.JFormattedTextField();
        lblLateTimeDel = new javax.swing.JLabel();
        pnlStops = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StopsTable = new javax.swing.JTable();
        btnAddStop = new javax.swing.JButton();
        pnlFreightInfo = new javax.swing.JPanel();
        lblBOL = new javax.swing.JLabel();
        txtBOL = new javax.swing.JTextField();
        lblWeight = new javax.swing.JLabel();
        txtWeight = new javax.swing.JFormattedTextField();
        chkTarp = new javax.swing.JCheckBox();
        lblHeight = new javax.swing.JLabel();
        spinHeight = new javax.swing.JSpinner();
        chkHazMat = new javax.swing.JCheckBox();
        chkTWIC = new javax.swing.JCheckBox();
        chkLTL = new javax.swing.JCheckBox();
        lblCommodity = new javax.swing.JLabel();
        txtCommodity = new javax.swing.JTextField();
        lblTruckPay = new javax.swing.JLabel();
        txtTruckPay = new javax.swing.JFormattedTextField();
        lblPerMile = new javax.swing.JLabel();
        txtPerMile = new javax.swing.JFormattedTextField();
        lblMiles = new javax.swing.JLabel();
        txtMiles = new javax.swing.JFormattedTextField();
        lblAgentPhone = new javax.swing.JLabel();
        txtAgentPhone = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setIconifiable(true);
        setTitle("New Load Entry");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pekinsoft/northwind/desktop/graphics/x16/Delivery.png"))); // NOI18N

        lblTrip.setText("Trip #:");

        txtTrip.setText("TRIP NUMBER");

        txtOrder.setText("ORDER NUMBER");

        lblOrder.setText("Order #:");

        lblBeginOdo.setText("Beginning ODO:");

        txtBeginOdo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###,##0"))));
        txtBeginOdo.setText("0000000");

        lblEndOdo.setText("Ending ODO:");

        txtEndOdo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        txtEndOdo.setText("0000000");

        pnlPickup.setBorder(javax.swing.BorderFactory.createTitledBorder("Pick-Up Info"));

        lblEarlyDatePU.setText("Early Date:");

        txtEarlyDatePU.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM/dd/yyyy"))));
        txtEarlyDatePU.setText("01/01/1970");

        lblEarlyTimePU.setText("Early Time:");

        txtEarlyTimePU.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH:mm"))));
        txtEarlyTimePU.setText("00:00");

        lblLateDatePU.setText("Late Date:");

        txtLateDatePU.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat(""))));
        txtLateDatePU.setText("01/01/1970");

        lblLateTimePU.setText("Late Time:");

        txtLateTimePU.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH:mm"))));
        txtLateTimePU.setText("23:59");

        javax.swing.GroupLayout pnlPickupLayout = new javax.swing.GroupLayout(pnlPickup);
        pnlPickup.setLayout(pnlPickupLayout);
        pnlPickupLayout.setHorizontalGroup(
            pnlPickupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPickupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPickupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLateTimePU)
                    .addComponent(lblLateDatePU)
                    .addComponent(lblEarlyTimePU)
                    .addComponent(lblEarlyDatePU))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPickupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEarlyDatePU, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(txtEarlyTimePU)
                    .addComponent(txtLateDatePU)
                    .addComponent(txtLateTimePU))
                .addContainerGap())
        );
        pnlPickupLayout.setVerticalGroup(
            pnlPickupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPickupLayout.createSequentialGroup()
                .addGroup(pnlPickupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEarlyDatePU)
                    .addComponent(txtEarlyDatePU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPickupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEarlyTimePU)
                    .addComponent(txtEarlyTimePU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPickupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLateDatePU)
                    .addComponent(txtLateDatePU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPickupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLateTimePU)
                    .addComponent(txtLateTimePU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlDelivery.setBorder(javax.swing.BorderFactory.createTitledBorder("Delivery Info"));

        lblEarlyDateDel.setText("Early Date:");

        txtEarlyDateDel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM/dd/yyyy"))));
        txtEarlyDateDel.setText("01/02/1970");

        txtEarlyTimeDel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH:mm"))));
        txtEarlyTimeDel.setText("00:00");

        lblEarlyTimeDel.setText("Early Time:");

        lblLateDateDel.setText("Late Date:");

        txtLateDateDel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat(""))));
        txtLateDateDel.setText("01/02/1970");

        txtLateTimeDel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH:mm"))));
        txtLateTimeDel.setText("23:59");

        lblLateTimeDel.setText("Late Time:");

        javax.swing.GroupLayout pnlDeliveryLayout = new javax.swing.GroupLayout(pnlDelivery);
        pnlDelivery.setLayout(pnlDeliveryLayout);
        pnlDeliveryLayout.setHorizontalGroup(
            pnlDeliveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeliveryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDeliveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLateTimeDel)
                    .addComponent(lblLateDateDel)
                    .addComponent(lblEarlyTimeDel)
                    .addComponent(lblEarlyDateDel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDeliveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEarlyDateDel, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(txtEarlyTimeDel)
                    .addComponent(txtLateDateDel)
                    .addComponent(txtLateTimeDel))
                .addContainerGap())
        );
        pnlDeliveryLayout.setVerticalGroup(
            pnlDeliveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeliveryLayout.createSequentialGroup()
                .addGroup(pnlDeliveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEarlyDateDel)
                    .addComponent(txtEarlyDateDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDeliveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEarlyTimeDel)
                    .addComponent(txtEarlyTimeDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDeliveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLateDateDel)
                    .addComponent(txtLateDateDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDeliveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLateTimeDel)
                    .addComponent(txtLateTimeDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlStops.setBorder(javax.swing.BorderFactory.createTitledBorder("Stop Off Info"));

        StopsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stop #", "Customer ID", "Early Date", "Early Time", "Late Date", "Late Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(StopsTable);
        if (StopsTable.getColumnModel().getColumnCount() > 0) {
            StopsTable.getColumnModel().getColumn(0).setResizable(false);
            StopsTable.getColumnModel().getColumn(1).setResizable(false);
            StopsTable.getColumnModel().getColumn(2).setResizable(false);
            StopsTable.getColumnModel().getColumn(3).setResizable(false);
            StopsTable.getColumnModel().getColumn(4).setResizable(false);
            StopsTable.getColumnModel().getColumn(5).setResizable(false);
        }

        btnAddStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pekinsoft/northwind/desktop/graphics/x16/add.png"))); // NOI18N
        btnAddStop.setText("Add Stop...");

        javax.swing.GroupLayout pnlStopsLayout = new javax.swing.GroupLayout(pnlStops);
        pnlStops.setLayout(pnlStopsLayout);
        pnlStopsLayout.setHorizontalGroup(
            pnlStopsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStopsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStopsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStopsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddStop)))
                .addContainerGap())
        );
        pnlStopsLayout.setVerticalGroup(
            pnlStopsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStopsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddStop)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlFreightInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Freight/Load Info"));

        lblBOL.setText("BoL #:");

        txtBOL.setText("BOL NUMBER");

        lblWeight.setText("Weight:");

        txtWeight.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##,##0 lbs."))));
        txtWeight.setText("00000 lbs.");

        chkTarp.setText("Tarp?");

        lblHeight.setText("Height:");

        spinHeight.setModel(new javax.swing.SpinnerNumberModel(0, 0, 8, 2));

        chkHazMat.setText("HazMat?");

        chkTWIC.setText("TWIC?");

        chkLTL.setText("LTL?");

        lblCommodity.setText("Commodity:");

        txtCommodity.setText("COMMODITY");

        lblTruckPay.setText("Truck Pay:");

        txtTruckPay.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤##,##0.00"))));
        txtTruckPay.setText("$0.00");

        lblPerMile.setText("Per Mile:");

        txtPerMile.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#0.00"))));
        txtPerMile.setText("$0.00");

        lblMiles.setText("Dispatch Miles:");

        txtMiles.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));

        lblAgentPhone.setText("Agent/Broker Phone Number:");

        try {
            txtAgentPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###) ###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout pnlFreightInfoLayout = new javax.swing.GroupLayout(pnlFreightInfo);
        pnlFreightInfo.setLayout(pnlFreightInfoLayout);
        pnlFreightInfoLayout.setHorizontalGroup(
            pnlFreightInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFreightInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFreightInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlFreightInfoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblTruckPay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTruckPay, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPerMile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPerMile, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMiles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMiles))
                    .addGroup(pnlFreightInfoLayout.createSequentialGroup()
                        .addComponent(lblCommodity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCommodity))
                    .addGroup(pnlFreightInfoLayout.createSequentialGroup()
                        .addComponent(lblAgentPhone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAgentPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFreightInfoLayout.createSequentialGroup()
                        .addGroup(pnlFreightInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFreightInfoLayout.createSequentialGroup()
                                .addComponent(chkTarp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblHeight)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkHazMat))
                            .addGroup(pnlFreightInfoLayout.createSequentialGroup()
                                .addComponent(lblBOL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBOL, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlFreightInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFreightInfoLayout.createSequentialGroup()
                                .addComponent(chkTWIC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkLTL)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFreightInfoLayout.createSequentialGroup()
                                .addGap(0, 34, Short.MAX_VALUE)
                                .addComponent(lblWeight)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFreightInfoLayout.setVerticalGroup(
            pnlFreightInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFreightInfoLayout.createSequentialGroup()
                .addGroup(pnlFreightInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBOL)
                    .addComponent(txtBOL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWeight)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFreightInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkTarp)
                    .addComponent(lblHeight)
                    .addComponent(spinHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkHazMat)
                    .addComponent(chkTWIC)
                    .addComponent(chkLTL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFreightInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommodity)
                    .addComponent(txtCommodity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFreightInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTruckPay)
                    .addComponent(txtTruckPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPerMile)
                    .addComponent(txtPerMile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMiles)
                    .addComponent(txtMiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFreightInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgentPhone)
                    .addComponent(txtAgentPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pekinsoft/northwind/desktop/graphics/x16/cancel.png"))); // NOI18N
        btnCancel.setMnemonic('C');
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButton_Clicked(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pekinsoft/northwind/desktop/graphics/x16/apply.png"))); // NOI18N
        btnSave.setMnemonic('S');
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButton_Clicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pnlFreightInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlStops, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblBeginOdo)
                                            .addComponent(lblTrip))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTrip, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                            .addComponent(txtBeginOdo)))
                                    .addComponent(pnlPickup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblEndOdo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEndOdo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblOrder)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(pnlDelivery, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTrip)
                    .addComponent(txtTrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrder))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBeginOdo)
                    .addComponent(txtBeginOdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEndOdo)
                    .addComponent(txtEndOdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlPickup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDelivery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlStops, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFreightInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButton_Clicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButton_Clicked
        Application.log.enter(LoadEntryDialog.class.getName(), "CancelButton"
                + "_Click", evt);
        Application.log.debug("Closing the \"New Load Entry\" dialog WITHOUT "
                + "saving the new load information...");
        Application.log.exit(LoadEntryDialog.class.getName(), "CancelButton"
                + "_Clicked");
        this.dispose();
    }//GEN-LAST:event_CancelButton_Clicked

    private void SaveButton_Clicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButton_Clicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveButton_Clicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable StopsTable;
    private javax.swing.JButton btnAddStop;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chkHazMat;
    private javax.swing.JCheckBox chkLTL;
    private javax.swing.JCheckBox chkTWIC;
    private javax.swing.JCheckBox chkTarp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgentPhone;
    private javax.swing.JLabel lblBOL;
    private javax.swing.JLabel lblBeginOdo;
    private javax.swing.JLabel lblCommodity;
    private javax.swing.JLabel lblEarlyDateDel;
    private javax.swing.JLabel lblEarlyDatePU;
    private javax.swing.JLabel lblEarlyTimeDel;
    private javax.swing.JLabel lblEarlyTimePU;
    private javax.swing.JLabel lblEndOdo;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblLateDateDel;
    private javax.swing.JLabel lblLateDatePU;
    private javax.swing.JLabel lblLateTimeDel;
    private javax.swing.JLabel lblLateTimePU;
    private javax.swing.JLabel lblMiles;
    private javax.swing.JLabel lblOrder;
    private javax.swing.JLabel lblPerMile;
    private javax.swing.JLabel lblTrip;
    private javax.swing.JLabel lblTruckPay;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JPanel pnlDelivery;
    private javax.swing.JPanel pnlFreightInfo;
    private javax.swing.JPanel pnlPickup;
    private javax.swing.JPanel pnlStops;
    private javax.swing.JSpinner spinHeight;
    private javax.swing.JFormattedTextField txtAgentPhone;
    private javax.swing.JTextField txtBOL;
    private javax.swing.JFormattedTextField txtBeginOdo;
    private javax.swing.JTextField txtCommodity;
    private javax.swing.JFormattedTextField txtEarlyDateDel;
    private javax.swing.JFormattedTextField txtEarlyDatePU;
    private javax.swing.JFormattedTextField txtEarlyTimeDel;
    private javax.swing.JFormattedTextField txtEarlyTimePU;
    private javax.swing.JFormattedTextField txtEndOdo;
    private javax.swing.JFormattedTextField txtLateDateDel;
    private javax.swing.JFormattedTextField txtLateDatePU;
    private javax.swing.JFormattedTextField txtLateTimeDel;
    private javax.swing.JFormattedTextField txtLateTimePU;
    private javax.swing.JFormattedTextField txtMiles;
    private javax.swing.JTextField txtOrder;
    private javax.swing.JFormattedTextField txtPerMile;
    private javax.swing.JTextField txtTrip;
    private javax.swing.JFormattedTextField txtTruckPay;
    private javax.swing.JFormattedTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
