/*
 * Copyright (C) 2020 PekinSOFT Systems
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * *****************************************************************************
 * *****************************************************************************
 *  Project    :   Northwind-Basic
 *  Class      :   MainFrame.java
 *  Author     :   Sean Carrick
 *  Created    :   Mar 11, 2020 @ 5:35:06 PM
 *  Modified   :   Mar 11, 2020
 *  
 *  Purpose:
 *  
 *  Revision History:
 *  
 *  WHEN          BY                  REASON
 *  ------------  ------------------- ------------------------------------------
 *  Mar 11, 2020  Sean Carrick        Initial creation.
 *  Mar 14, 2020  Sean Carrick        Added the New menu, under the File menu,
 *                                    as well as the Customer Entry menu item,
 *                                    under the New menu.
 * *****************************************************************************
 */
package com.pekinsoft.northwind.desktop;

import com.pekinsoft.northwind.basic.Application;
import com.pekinsoft.northwind.utils.enums.SysExits;
import com.pekinsoft.northwind.utils.exceptions.InvalidLoggingLevelException;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sean Carrick
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        Application.log.enter(MainFrame.class.getCanonicalName(), "Constructor");
        Application.log.debug("Initializing frame components...");
        initComponents();
        
        Application.log.debug("Setting the MainFrame icon to:\n\n\t"
                + "/com/pekinsoft/northwind/desktop/graphics/x16/Northwind.png");
        this.setIconImage(Toolkit
                .getDefaultToolkit()
                .getImage(getClass()
                        .getResource(
                                "/com/pekinsoft/northwind/desktop/graphics/x16/"
                                        + "Northwind.png")));
        this.setTitle(Application.TITLE + " " + Application.EDITION 
                + " (Build " + Application.BUILD + ")");
        
        Application.log.exit(MainFrame.class.getCanonicalName(), "Constructor");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StatusBar = new javax.swing.JToolBar();
        StatusLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        TotalRevenuePrompt = new javax.swing.JLabel();
        TotalRevenueLabel = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        RevenuePerMilePrompt = new javax.swing.JLabel();
        RevenuePerMileLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        TotalExpensesPrompt = new javax.swing.JLabel();
        TotalExpensesLabel = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        ExpensesPerMilePrompt = new javax.swing.JLabel();
        ExpensesPerMileLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        TotalProfitPrompt = new javax.swing.JLabel();
        TotalProfitLabel = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        ProfitPerMileLabel = new javax.swing.JLabel();
        MainDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        NewMenu = new javax.swing.JMenu();
        NewCustomerMenuItem = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        ExitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Application Frame");

        StatusBar.setFloatable(false);
        StatusBar.setRollover(true);

        StatusLabel.setText("<html>Watch here for helpful tips...");
        StatusLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        StatusLabel.setMaximumSize(new java.awt.Dimension(750, 20));
        StatusLabel.setPreferredSize(new java.awt.Dimension(500, 20));
        StatusBar.add(StatusLabel);

        jSeparator1.setSeparatorSize(new java.awt.Dimension(25, 10));
        StatusBar.add(jSeparator1);

        TotalRevenuePrompt.setText("Total Revenue:");
        StatusBar.add(TotalRevenuePrompt);

        TotalRevenueLabel.setText("$ 0.00");
        TotalRevenueLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        StatusBar.add(TotalRevenueLabel);

        jSeparator6.setSeparatorSize(new java.awt.Dimension(3, 10));
        StatusBar.add(jSeparator6);

        RevenuePerMilePrompt.setText("Per Mile:");
        StatusBar.add(RevenuePerMilePrompt);

        RevenuePerMileLabel.setForeground(new java.awt.Color(0, 51, 255));
        RevenuePerMileLabel.setText("$ 0.00");
        RevenuePerMileLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        StatusBar.add(RevenuePerMileLabel);
        StatusBar.add(jSeparator2);

        TotalExpensesPrompt.setText("Total Expenses:");
        StatusBar.add(TotalExpensesPrompt);

        TotalExpensesLabel.setText("$ 0.00");
        TotalExpensesLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        StatusBar.add(TotalExpensesLabel);

        jSeparator5.setSeparatorSize(new java.awt.Dimension(3, 10));
        StatusBar.add(jSeparator5);

        ExpensesPerMilePrompt.setText("Per Mile:");
        StatusBar.add(ExpensesPerMilePrompt);

        ExpensesPerMileLabel.setForeground(new java.awt.Color(0, 51, 204));
        ExpensesPerMileLabel.setText("$ 0.00");
        ExpensesPerMileLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        StatusBar.add(ExpensesPerMileLabel);
        StatusBar.add(jSeparator3);

        TotalProfitPrompt.setText("Total Profit:");
        StatusBar.add(TotalProfitPrompt);

        TotalProfitLabel.setText("$ 0.00");
        TotalProfitLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        StatusBar.add(TotalProfitLabel);

        jSeparator4.setSeparatorSize(new java.awt.Dimension(3, 10));
        StatusBar.add(jSeparator4);

        jLabel1.setText("Per Mile:");
        StatusBar.add(jLabel1);

        ProfitPerMileLabel.setForeground(new java.awt.Color(0, 51, 204));
        ProfitPerMileLabel.setText("$0.00");
        ProfitPerMileLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        StatusBar.add(ProfitPerMileLabel);

        javax.swing.GroupLayout MainDesktopLayout = new javax.swing.GroupLayout(MainDesktop);
        MainDesktop.setLayout(MainDesktopLayout);
        MainDesktopLayout.setHorizontalGroup(
            MainDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        MainDesktopLayout.setVerticalGroup(
            MainDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 727, Short.MAX_VALUE)
        );

        FileMenu.setText("File");

        NewMenu.setText("New");

        NewCustomerMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        NewCustomerMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pekinsoft/northwind/desktop/graphics/x16/users.png"))); // NOI18N
        NewCustomerMenuItem.setMnemonic('C');
        NewCustomerMenuItem.setText("Customer...");
        NewCustomerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCustomerMenuItem_Clicked(evt);
            }
        });
        NewMenu.add(NewCustomerMenuItem);

        FileMenu.add(NewMenu);
        FileMenu.add(jSeparator7);

        ExitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        ExitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pekinsoft/northwind/desktop/graphics/x16/exit.png"))); // NOI18N
        ExitMenuItem.setMnemonic('x');
        ExitMenuItem.setText("Exit");
        ExitMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMenuItemMouseExited(evt);
            }
        });
        ExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(ExitMenuItem);

        jMenuBar1.add(FileMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StatusBar, javax.swing.GroupLayout.DEFAULT_SIZE, 1243, Short.MAX_VALUE)
            .addComponent(MainDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(MainDesktop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatusBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuItemActionPerformed
        Application.log.enter(MainFrame.class.getName(), "ExitMenuItemAction"
                + "Performed", evt);
        Application.log.debug("Setting the MainFrame to no longer being "
                + "visible...");
        this.setVisible(false);
        Application.log.debug("Calling the Application.exit() method...");
        Application.log.exit(MainFrame.class.getName(), "ExitMenuItemAction"
                + "Performed");
        Application.exit(SysExits.EX_OK);
    }//GEN-LAST:event_ExitMenuItemActionPerformed

    private void ExitMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMenuItemMouseEntered
        StatusLabel.setText("<html>Click this menu item to exit Northwind "
                + "Traders. <strong>Alternatively, press Alt+F4 on your "
                + "keyboard.");
    }//GEN-LAST:event_ExitMenuItemMouseEntered

    private void ExitMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMenuItemMouseExited
        StatusLabel.setText("<html>Watch here for helpful tips...");
    }//GEN-LAST:event_ExitMenuItemMouseExited

    private void NewCustomerMenuItem_Clicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCustomerMenuItem_Clicked
        Application.log.enter(MainFrame.class.getName(), "NewCustomerMenuItem"
                + "_Clicked", evt);
        Application.log.debug("Creating an instance of the CustomerEntryDialog...");
        CustomerEntryDialog dlg = new CustomerEntryDialog();
        Application.log.debug("Adding the new CustomerEntryDialog to the "
                + "MainDesktop for display...");
        this.MainDesktop.add(dlg);
        Application.log.debug("Packing and showing the CustomerEntryDialog...");
        dlg.pack();
        dlg.setVisible(true);
        Application.log.exit(MainFrame.class.getName(), "NewCustomerMenuItem"
                + "_Clicked");
    }//GEN-LAST:event_NewCustomerMenuItem_Clicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Application.log.enter(MainFrame.class.getCanonicalName(), "main");
        Application.log.config("Setting the look and feel to the system default.");
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Application.log.error(ex, "Class Not Found");
        } catch (InstantiationException ex) {
            Application.log.error(ex, "Instantiation Error");
        } catch (IllegalAccessException ex) {
            Application.log.error(ex, "Illegal Access");
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            Application.log.error(ex, "Unsupported Look and Feel");
        }
        //</editor-fold>

        /* Create and display the form */
        Application.log.config("Starting the event queue...");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Application.log.debug(">>>>>Displaying the MainFrame...<<<<<");
                new MainFrame().setVisible(true);
            }
        });
        Application.log.exit(MainFrame.class.getCanonicalName(), "main");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ExitMenuItem;
    private javax.swing.JLabel ExpensesPerMileLabel;
    private javax.swing.JLabel ExpensesPerMilePrompt;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JDesktopPane MainDesktop;
    private javax.swing.JMenuItem NewCustomerMenuItem;
    private javax.swing.JMenu NewMenu;
    private javax.swing.JLabel ProfitPerMileLabel;
    private javax.swing.JLabel RevenuePerMileLabel;
    private javax.swing.JLabel RevenuePerMilePrompt;
    private javax.swing.JToolBar StatusBar;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JLabel TotalExpensesLabel;
    private javax.swing.JLabel TotalExpensesPrompt;
    private javax.swing.JLabel TotalProfitLabel;
    private javax.swing.JLabel TotalProfitPrompt;
    private javax.swing.JLabel TotalRevenueLabel;
    private javax.swing.JLabel TotalRevenuePrompt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
